### ISSUE TITLE
Feedback doesn't work

### ISSUE THREAD

**Issue by larsvdmanden** [bitfocus/companion-module-audivero-unityintercom-client#1]
Hello!

With the latest version of Companion (companion-2.2.0-77e29ef4-3230, windows and mac) I am struggling with getting feedback from Unity on the pressed buttons. Am I the only one with this problem? In the attached files some screendumps of the instance where I should expected some red and blue buttons. I tried with all the feedback options (red and blue, only red and only blue).

Thanks for helping me out/fixing the bug!

Lars.
<img width="1514" alt="Schermafbeelding 2021-04-06 om 22 56 30" src="https://user-images.githubusercontent.com/58793484/113778118-4d874d00-972c-11eb-8057-c2ac35c6960b.png">
<img width="772" alt="Schermafbeelding 2021-04-06 om 22 56 38" src="https://user-images.githubusercontent.com/58793484/113778126-50823d80-972c-11eb-9e6e-6aa1e85f0019.png">

**Comment by JeffreyDavidsz** [comment]
@josephdadams

**Comment by josephdadams** [comment]
Did you use the presets to make the buttons or did you make them yourself?

**Comment by larsvdmanden** [comment]
Oh, I did it myself earlier this week with the previous beta of Companion. That wasn't working. The buttons made with presets are working indeed. :) That's great, thanks.

**Comment by larsvdmanden** [comment]
But to be complete: it doesn't work when I program exact the same as the preset manually.

**Comment by krocheck** [comment]
@larsvdmanden when you program it manually and it doesn't seem to work, will it light up if you cycle that listen off then on for the channel in the app?
