### ISSUE TITLE
Fails to close udp socket

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-audivero-unityintercom-client#4]
https://github.com/bitfocus/companion-module-audivero-unityintercom-client/blob/0bb64e60c747591a44bc1d3c2e3139e9fa34bcec/index.js#L339

I am 99% sure that `self.udp.socket` is not valid and will always be undefined (it was for me in a quick test locally, and docs make no mention of it).
This means that the `self.udp.close()` will never be called and will cause the socket to be leaked, and will cause any attempts to rebind to the same port to fail

https://www.facebook.com/groups/companion/permalink/2847874082097590/

**Comment by josephdadams** [comment]
Is that line even needed then?

**Comment by Julusian** [comment]
If you make it be `self.udp.removeAllListeners(); then it is valid, but I have no idea if there is any benefit to having it compared to simply removing the line

**Comment by josephdadams** [comment]
I removed the line
