### ISSUE TITLE
Cannot connect if companion interface is set to anything other than local.

### ISSUE THREAD

**Issue by swperic** [bitfocus/companion-module-audivero-unityintercom-client#5]
Please forgive me if I am doing something wrong but I cannot get companion and unity to talk unless companion is set to 127.0.0.1.  
I get this error.
Network error: bind EADDRINUSE 0.0.0.0:20119

**Comment by VideoVillageCreative** [comment]
I have the same issue. Would love to hear if anyone has been able to rectify this.

> Please forgive me if I am doing something wrong but I cannot get companion and unity to talk unless companion is set to 127.0.0.1.
> I get this error.
> Network error: bind EADDRINUSE 0.0.0.0:20119

**Comment by nick-rutter** [comment]
Same for me on Pi4. +1

**Comment by murray484** [comment]
I'm also having this issue.

**Comment by dcabrera-halfbit** [comment]
Have you confirmed that you entered the Companion server's IP Address in Unity Intercom Client? I recently discovered that this is a two-step process to work with Companion.

First, you need to point the Companion Instance of Unity Intercom towards the client IP address (it can be the local IP or a remote IP).

Then, you open up Unity Client (you need to be actively connected to your Unity Intercom setup as this step is not in the Settings menu), hit the Hotkeys menu item and there should be an option to enter in an IP address to point towards a local/remote Stream Deck/Companion server.

Here's the hyperlink on Unity's website that explains it: https://www.unityintercom.com/unity-tech-notes/remote-stream-deck-control-for-mac-and-windows-clients

I hope this helps!
