### ISSUE TITLE
Audivero Unity Intercom Client

### ISSUE THREAD

**Issue by CPanic1** [bitfocus/companion-module-audivero-unityintercom-client#6]
The Audivero Unity Intercom Client either stays stuck on connecting or gives this error when companion is run on a computer other than where the unity client is.  Windows 10
Network error: bind EADDRINUSE 0.0.0.0:20119

**Comment by josephdadams** [comment]
This is an issue with that port already being used for something else.

**Comment by josephdadams** [comment]
This may also help: https://www.unityintercom.com/unity-tech-notes/remote-stream-deck-control-for-mac-and-windows-clients
