### ISSUE TITLE
Can only connect single instance to single Unity client

### ISSUE THREAD

**Issue by cpuguru07** [bitfocus/companion-module-audivero-unityintercom-client#7]
If I try to connect multiple instances of this module (from a single Companion server) to different Unity clients (on different PCs), the first one connects fine, and then the rest get the error:
Network error: bind EADDRINUSE 0.0.0.0:20119

I need to be able to connect to multiple Unity clients, as all of our StreamDecks are controlled by a single Companion server.

**Comment by josephdadams** [comment]
Sorry, but it’s a limitation of the Unity protocol. Their program sends out a multicast UDP poll to port 20119. The Companion module listens on this port and responds with a subscription message, and the Unity program then responds back specifically to that IP on the same port. On the Companion side it only ever uses that one port. So there isn’t a way for multiple instances of this module to interact without all of the instances talking to each other and sharing data and that isn’t in the Companion ecosystem. 

I can add better error handling though so you don’t get the error message. But until they implement a better protocol, that’s basically your option.

**Comment by srmorris2** [comment]
@josephdadams Is there a known way to remap or change the port the Unity instance uses? We were working to switch to a single companion server with Satallite, and this issue with Unity makes it impossible for us to do that.

**Comment by josephdadams** [comment]
Not that I know of. You could try reaching out to Unity. I gave them some protocol suggestions back when they hired me to make this module.
