### ISSUE TITLE
RELEASE of "All Page" button doesn't always release

### ISSUE THREAD

**Issue by srmorris2** [bitfocus/companion-module-audivero-unityintercom-client#8]
I was testing some new ideas for our users, and noticed that when the ALL PAGE is used as a button, it doesn't always release. If you hold the button for more than a second, the PAGE gets stuck on. I've got a workaround for now by placing an additional press and release with 5ms delays in the "Release Actions" and that is making sure it stops the page action from Unity.

**Comment by josephdadams** [comment]
Companion sends the same command no matter what the button actually does - it doesn't even really know what the function of the button is, that is up to Unity. So I would say that this is a Unity client issue.
